/*
 * generated by Xtext 2.12.0
 */
package br.ufes.inf.nemo.wpcmLanguage.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class WpcmScopeProvider extends AbstractWpcmScopeProvider {

}
