/*
 * generated by Xtext 2.12.0
 */
package br.ufes.inf.nemo.wpcmLanguage


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WpcmRuntimeModule extends AbstractWpcmRuntimeModule {
}
