/*
 * generated by Xtext 2.12.0
 */
package br.ufes.inf.nemo.wpcmLanguage


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WpcmStandaloneSetup extends WpcmStandaloneSetupGenerated {

	def static void doSetup() {
		new WpcmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
